# Generated by Django 6.0.2 on 2026-03-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='last_sampled_questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
