# Generated by Django 6.0.2 on 2026-03-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_interviewsession_last_sampled_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='expected_keywords',
            new_name='keywords',
        ),
        migrations.RemoveField(
            model_name='question',
            name='model_answer_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='model_answer_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='model_answer_3',
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
