# Generated by Django 6.0.2 on 2026-03-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_rename_expected_keywords_question_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='last_sampled_questions',
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='incorrect_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='partial_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='current_difficulty',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
