# Generated by Django 6.0.2 on 2026-03-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_remove_interviewsession_last_sampled_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='last_sampled_questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
