# Generated by Django 6.0.2 on 2026-03-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_interviewsession_last_sampled_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ideal_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(max_length=20),
        ),
    ]
